baseURL = "https://blog.nathanisaac.io/"
languageCode = "en-us"
title = "Nathan Isaac"
theme = "ezhil"

copyright = "© 2021 Nathan Isaac"

# Enable syntax highlighting.
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
#googleAnalytics = "UA-123-45"
# Your Disqus sortname.
#disqusShortname = "localhost"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
# Blog subtitle which appears below blog title. Supports markdown.
subtitle = "Software engineer specialing in web application development."

# Content types which are included in home page recent posts list.
mainSections = ["articles"]

# Content types which are excludes Disqus comments.
disableDisqusTypes = ["page"]

# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
featherIconsCDN = false

# Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
#favicon = "icons/myicon.png"

# Switch to dark mode or auto detect mode from OS (Optional).
# "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
mode = "auto" # "dark" or "auto"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/articles"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nathanjisaac"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nathanjisaac"

[[params.social]]
name = "RSS FEED"
icon = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
tag = "tags"

